# Generated by Django 3.2.25 on 2025-06-30 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('url_id', models.AutoField(primary_key=True, serialize=False)),
                ('original_url', models.URLField(max_length=255, unique=True)),
                ('shortened_code', models.CharField(max_length=20, unique=True)),
                ('clicks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
